services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=Psimple_blog_api
            - POSTGRES_USERNAME=postgres
    api:
        context: ./
        dockerfile: Dockerfile
        build:
        image: docker.io/ravi/simple_blog-api
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
          ports:
            - "3000:3000"
            