Drop table zipcodes;
CREATE TABLE zipcodes (RecordNumber int, Country string, City string, Zipcode int) PARTITIONED BY (state string) CLUSTERED BY (Zipcode) INTO 3 BUCKETS ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INPATH '/root/zipcodes.csv' INTO TABLE zipcodes;
SHOW PARTITIONS zipcodes;
INSERT OVERWRITE LOCAL DIRECTORY '/root/HiveOutput9' ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' SELECT * FROM zipcodes where state='PR' and Zipcode=704;