services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: redis
        command: ["redis-server", "--protected-mode", "no"]
    api:
        build: ./server
        image: docker.io/ravi/complex-api
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    #React Client
    client:
        build: ./client
        image: docker.io/ravi/complex-client
    #React Worker
    worker:
        build: ./worker
        image: docker.io/ravi/complex-worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    #Nginx Service
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build: ./nginx
        image: docker.io/ravi/complex-nginx
        ports:
            - '8082:80'